### ISSUE TITLE
HttpRequestException: statsapi.web.nhl.com is not available

### ISSUE THREAD

**Issue by mlynarp** [Afischbacher/Nhl.Api#41]
Today the nuget package stopped working and it looks like that NHL changes API endpoint.

https://gitlab.com/dword4/nhlapi/-/issues/110#note_1572143580

**Comment by Afischbacher** [comment]
Hey @mlynarp 

Thank you for bringing this to my attention, it looks like we need to do some serious remodeling of this NuGet.

I will see what the extent of the damage is sometime tonight.

Thanks again,

Andre

**Comment by cook-t** [comment]
Hey @Afischbacher - any update on the timeframe for the fix? Thanks!

**Comment by Afischbacher** [comment]
Hey @cook-t  and @mlynarp 

I hope you're all doing well. I wanted to provide an update on the current status of the project and discuss some key decisions that need to be made.

My primary objective is to have a Minimum Viable Product (MVP) up and running within the next few days, ideally by the end of this coming week. As part of this process, a new version of the NuGet package should be published.

I'm currently in the process of assessing the situation, and there are a few crucial choices that I need to make:

Versioning Strategy:
Considering the significant changes in the HTTP REST endpoint, I'm contemplating the creation of a `v2` for the `NhlApi`. This decision will impact the overall structure and functionality of the API.

Model Mapping:
With potential variations in payloads due to the new endpoints, it seems inevitable that we'll need to create all-new models for effectively mapping these changes. This is a critical step to ensure seamless integration with the updated API.

I welcome your input and insights on these decisions.

Thanks everyone for understanding 

Andre,

**Comment by mlynarp** [comment]
I fully support new version v2 that makes perfect sense. For simplicity you can adapt models to better fit new API, if there is a way to retrieve same data as now. 

I personally use this package to retrieve data for NHL Fantasy league on Yahoo. Mostly interested in player stats and game schedule. 

It would be great to integrate also Faceoffs as I proposed in second issue. 

Thanks.

**Comment by Afischbacher** [comment]
Hey @cook-t and @mlynarp,

I hope you are doing well. I wanted to share an update on the progress of the NuGet.

Regarding API versioning, a key consideration currently revolves around the uncertainty of the NHL's decision to revive or re-enable `statsapi.web.nhl.com`. Given this, I see little merit in retaining all the old endpoints in the codebase. Resolving this involves breaking down and rebuilding the currently failing endpoints.

Complicating matters further, the original maintainer of the NHL API documentation on GitLab, Drew Hynes (https://gitlab.com/dword4), is actively working on compiling public endpoints while navigating CORS challenges. This restricts the scope of what I can implement at this time.

These changes also require me to redocument for many items in the API, demanding time and effort.

As for the timeline, my life and career are quite hectic. I understand the urgency in getting the NuGet back up and running, and I'm committed to completing it as swiftly as possible.

If anyone is willing to contribute and assist in any capacity, I'd greatly appreciate the support.

Thank you all for your understanding.

Best Regards,
Andre

**Comment by mlynarp** [comment]
Hey,

I might help you if needed but I am not aware how to solve CORS challange.

**Comment by Afischbacher** [comment]
Hey @mlynarp,

For now I am ok, if I need anything, I will reach out, just trying to find time to work through all the changes

**Comment by mlynarp** [comment]
Hey,

any news or possible time frame for the API fix? 

I lost three weeks in NHL Fantasy league in a row. It looks I am blind without the stats :-)

**Comment by Afischbacher** [comment]
Hey @mlynarp,
 
I apologize for the delays here, I have been dealing with the hectic nature of life. My goal now is to have this out by the end of the year, or at least an minimal viable product as soon as possible.

Thanks

**Comment by Afischbacher** [comment]
Hello @cook-t and @mlynarp,

I wanted to share an exciting update with you. I'm actively working on a new release scheduled for the next 7 to 10 business days! I'll keep you posted as I gather more information.

While this upcoming release is set to be an MVP, it promises to keep the excitement alive as we transition into the New Year for the NHL API.

Thank you for your continued support!

Best regards,
Andre

**Comment by stuginho** [comment]
Hey, any update?
Cheers

**Comment by Afischbacher** [comment]
Hey @stuginho 

Still pushing through it and I'm almost done within the next few days 

Thanks for your patience

**Comment by Afischbacher** [comment]
@cook-t @stuginho @mlynarp 

Hey everyone!

Looking forward to pushing out the `3.0.0` update within the next few hours!

Thanks again for all your patience!

**Comment by Afischbacher** [comment]
@cook-t  @stuginho  @mlynarp 

Hello again!

The NuGet package is now live, please make updates accordingly and have fun doing it! 

Link: https://www.nuget.org/packages/Nhl.Api

I will be closing this issue now!

Thanks
